# For development
version: "2"
services:
  redis:
    image: bitnami/redis
    environment:
      - REDIS_PASSWORD=pass
    volumes:
      - ./data:/bitnami/redis/data
    ports:
      - "6379:6379"

  isthisapple:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_APPLES_URL=redis://:pass@redis:6379
      - REDIS_URL=redis://:pass@redis:6379/1
      - SECRET=development
      - S3_BUCKET=isthisapple
      - AWS_ACCESS_KEY_ID=access_key
      - AWS_SECRET_ACCESS_KEY=secret_key
    depends_on:
      - redis
    volumes:
      - .:/srv
    links:
      - redis
    entrypoint:
      - python3
      - main.py

  front:
    image: node:11.6.0-alpine
    ports:
      - "3000:3000"
    working_dir: /home/apples
    volumes:
      - .:/home/apples
    command: npm start
