name: Node.js CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js v10.x
      uses: actions/setup-node@v1
      with:
        node-version: v10.x
        
    - name: Setup BIT
      run: npm config set @bit:registry https://node.bitsrc.io
    
    - name: Instal dependencies
      run: npm install

    - name: Build
      run: npm run build --if-present
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./build
